---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 21.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    production: true
    proxyHeaders: xforwarded
    postgresql:
      enabled: false
    externalDatabase:
      existingSecret: keycloak-postgres
      existingSecretHostKey: host
      existingSecretPortKey: port
      existingSecretUserKey: user
      existingSecretDatabaseKey: dbname
      existingSecretPasswordKey: password
    sidecars:
      - name: cloudflared
        image: cloudflare/cloudflared:2024.6.1
        command:
        - cloudflared
        - tunnel
        # In a k8s environment, the metrics server needs to listen outside the pod it runs on.
        # The address 0.0.0.0:2000 allows any pod in the namespace.
        - --metrics
        - 0.0.0.0:2000
        - --no-autoupdate
        - run
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
          # Cloudflared has a /ready endpoint which returns 200 if and only if
          # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflared-keycloak
                key: tunnel-token
