apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Tb4mR6WNeUfP55B7W31Z9JQHWbELCnYSdjNU20B1+wTYqROR,iv:pASWfzSFeDfBja1vVwPciSG6sFLjicvGWwflSfa6dIs=,tag:iJhyGDvT2ae1ZkbcCzd3vA==,type:str]
    credentials.json: ENC[AES256_GCM,data:1yHTt5ttkQveusz73D88EU7HHLsOIHYrRVgjHGr9tHcigGJOB85LFfBIl2Zg8JN9kgE/SdX0x3DIOcYi0xSs++PWNU6K9tVGe7uV1DVxsLv1t9zRrVZp9C2JfBJuSJtSVu4sCO51NllfpQaB6EJxm3rgi3GsUjSazHIJOP1vy05+pOePKlTFyDHDwTvLvSMV9408EW0udyep+JlW2t1jec4towfIz3ZBE4xPtFbhdQ==,iv:21N+kf9AGcOtIU7rSTjr/el+TeHEY6aRhyF/PzXaNjQ=,tag:p4NKGQGcE7u3Wt+dXnPmFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTDQ2WnVzbUxwUEVtc0g5
            NWpINGpBb2FvWTNtMEp6Sy9WVUhCbENmd1RnCmNOZFFpckw0VU1EVHVFWEVUc3VW
            NHFpZnBHTHBTOWl6SXBVM2JPbVV5VGMKLS0tIGpIa2RUVTF3VkZLeUJXbEFQZDRY
            SHVZUXdkOUdIbUVDYVlKKzZRd1M0TmsKpPnc6m0shBMBMtCiV7IVtEMVxE+gx/Bp
            nVAvG5QY1zBfqQzQ1gG/Aewm55SYcihTRBWCtrPItwFLelD/fX4ebA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T11:35:38Z"
    mac: ENC[AES256_GCM,data:roPAwpqeNCOomj0ls6wyLWeiheHZy2VqpYQ/4pugx/5V/KGfdR238oRuOeZqS4MslsmFWoDgDjqh7/FJ0jOd6YCttL5ZxgT60OQ6xR3OYJFKRUjBYD/zUo5/9l3M9yYFVmR1eIVce1bbQnlSv8vtNji1C7IvXC+dnaLJrDFltF4=,iv:rw7kVK85GVZxa0X+SoW4Gfx26CE2bmpNZF6atrf+fFM=,tag:qgxRZDOZUTN/7lRxvo2NqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
