apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hl1FDd/UhsQfOhU6OysoDILGzhaYWSrUcqblcKfCsp7MoeKE,iv:5lgQxTPzqKjXqWOrwIOHD58boifp+7d5d1aGguvxg2E=,tag:eCsFzbSmG3FW+Lkj4ve95w==,type:str]
    credentials.json: ENC[AES256_GCM,data:xJF9FvF6VF2R/NlFouCqtoe4lKoi+/8PkXMIWdMaNz8W1E02WPSWgI5pPYLlz38dFxMKwlPHCbbfZH20sTa5q6cLxolrk31Dqy2RjOJ9QJsiW98phPZ+J7SYCzpt0TjiBAAWURzyU/Jg4V4OWvoOw0fJlWRp6Q3hPFyUVPThsZcUPvL2qEoqI52SkUiVbgEQLJl15u/VmphrR/cEx4KjpWsTm+Rf41ovhwDGQTYtfg==,iv:Gv79KDiFfvnNwqoU88DaemXYAw7AG6u8JTJvVzeafIY=,tag:zYPDxaMfmio1xvpoLCHEyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR0tONnd4SFQrdlVtYVEw
            TzhCT2tXQ2had1lJaXNlWDlZZnk0dmxhRnowCmFNV1YvUXoraDYrQ1VkMjduN3Zx
            VzFGZmZXMzZ5M0xFRUpkS2RjeHE3UUEKLS0tIDBKdURzSnhaRmtlUnI2blhYOHdI
            TjZvb0NVM01qMGpJLzAvWWFrZVVGWTgKGKWcWPQVg0hojzaoY8uXGWCVJFNKWAam
            3dtBcvFLR4j0C4PmzupDyel028T+26fds1Yur19PBHBvsAqiiVQCZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T20:30:12Z"
    mac: ENC[AES256_GCM,data:ArUXLIcthDKdu08gRw0uJJCnObxQCJaWX1kp4wEf7Iedk3ZLOAGNFBCJPk4ZCZU8ygjARdXTBENtRxNhwgABDWFpZWeLcuM46CqGxnokdKDd8orGwgezriTGVnBKl7OzltmpUmfLfmF0vg35e23WbIxcq4fBwQRhMvZ2rfh1V9o=,iv:AkMV0czeaoZLMWP/WhnVcycMK/NvQnOT/5p1j5YgNQI=,tag:yAoShxZHE/le0EZettNMag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
