apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zedptpHPdIhm8HUtd7bng1/jhxh+EGBIuoqloUBR2eslVHcD,iv:3CIf1iQCQTl5SzZiRpKtdM+K4Q1pxWhE48hmm9rInj0=,tag:5URTE9jGEyiK899lU/u+Yw==,type:str]
    credentials.json: ENC[AES256_GCM,data:tFEHoEj0ZJ1D6u6MzTjBtiMXfaW0Bdr6EAqdte+JHz9OMMTl8eBrmYJ1vKHt4Un+gisvKw9Ug3a1MnodI10dk1uDfw0GpoITpt8OVPvh/h/MHVfObuDT4/HhtaWk58+ohXDkt98yiysdahUFJ3oNDYc6zOrEuSGq6Ec6ioEJtCNJzhjisRm8nDrMscokoAuCmyURJi7IUeTeWL4YGxL1weoYbxKzsHfbQ0xlgnVdcw==,iv:PF/aR3UgMB9euUucj2rFDumbn/GR2fuBucy+DVed78k=,tag:bFfw7QCTm8php1VcvxOoLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmxod0lCcjhoR2dUWW9P
            MURSUjhWUDVHckRYRW40MDV4YW9jZDFZTHhzCkd0eUpQbG9VY1BuMzkwYk9qZzVX
            N1ExbFVmVDlWc3lkUkc3RW9CdnF6bk0KLS0tIEZyajRteTVPSkx4anRFZGl5c0RW
            OFY5d2k2cWlYV0lYQWFKUlpEZjhtd2MKSm0Pt9vxUkLYNWQR/jiK2U5v5glvdnoS
            5GEKwA0Mbm2pfm8WJ8vIFfrGGt/s06V55oSIU4930hq8kOD5DD8bqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T13:15:46Z"
    mac: ENC[AES256_GCM,data:sQBcErgnyynwEpZ48DNYNK7kVezb7bKfTONlcAiCebfHjLlFoCdHMOQmeYuqppH8tEzwfZs/TycrdMKw9s4RqnIlSbslr2nOxpYvp3tQcJnUh1mol4dGkFf1xF0RhqnGkMr4KTQOgCPjq/eL1szAPkhGwYiQ3DJAhWqJcHYVJCs=,iv:g9yPVnwGNRdb1Z9iJjQn9zQ3s1VXRqZoKTqMR9MKMZE=,tag:yBFFVCYlBHIm7LGybOLbxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
