apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5foVqzMQxCguVYaqM1ufih7OEBtF6D1KqET7o/56PRvicgygSi99zQ==,iv:vHOR5i7/cFeYNUin/hE1QXwb2zxcOYfqAZLycZjQUr0=,tag:twvp+dFrm21RXczGVFYmyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUhSQ3ovNHdUdkhoT3FY
            aU5PeTFmNUR4Zm9oSXVSZC9CbVhEUmlkTEEwCnhMUnlQZWhiZjI1emJhVzlsT2NI
            OWFaWWhKMVVlZ3lkNmk2dmI0Mk50VVEKLS0tIE9xem42LzdnQ05zbVJBK2s4MlVi
            MTVmRGxoV0kvSktFM1YreWFDWHNZWUkKwpa3+qsUs03icidWePfDntJzyXzhZi1C
            V4ou8gR6UJplswWiHf06zGhRUwIw9iZrHE+l7/cCZap0xhOFXVD+og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T20:30:12Z"
    mac: ENC[AES256_GCM,data:6N99y0LhvGmZJWV8S7L7+Y71CCLS6i2VLWZMY26LOoT3jUKtL26m71m533pmukAPDOviGaKx+0OkfjzRZ4ON/Ew5ZG8H0xNvFNpqAfTSYioan67vRx1mzU5ZCmQjd5IXCuSCD6sJpj2Fg1RRtt4HU6hswBHygYQiB5/BM4RQ6pM=,iv:ZA+3mVqH8QjosiGylSStTbP3semA3h0fJBGHxW8/Hs4=,tag:vAIEVIGzdDGyusFRc4bzZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
