apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:pdAjdCCfiXUlaF0XuGHvtNlwUejdpw/k/ztn8QBRBPmlkviDaWy/hQ==,iv:yLm0RRK80ydAjN8bVmP3UIhpenVnCOnunsGS0VVmsRo=,tag:AFuw6LsWtP6ZOxUUldgcGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHK1UzNm1xUktTbXgzRFZi
            R0x0Qk1YVUdzVGRVemtTeHdRRTBlbmxZUmdJCkJJN1ZEQmJXcitjZ0RsZDI2cS9a
            K2xFOG41T1JZSEQxTTFlMnREUUV6NTgKLS0tIFJKRVRJY2JOYVJpc3lKTmxjUWU1
            VWpRWkY5ZnV6VHZvNDEyL0lab0dSVlEKDGz/eLN9ZHX8QvTQ+evgPrzXDlUbG3Cc
            oxY1w5pXrZKQ1gqB67jCzNgmHzx6ts7I6jJYNsG5nLm79aQDSYFr4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T21:15:19Z"
    mac: ENC[AES256_GCM,data:zTeUCWtJmmvatSFlFObAlTTmYquNHKMmNyFAeEpVxRPhjl1K/YwccgfzwTbXsMDLZ8JJS6e5w2QwAdv1JSPVX65BIAhXCjihf2C9sLFA/DHxhXiM/CosqrSwbVV+y+qzd7oiPg8mMPeTAUeIrqWdVJfwhtksAdWlmGAbC4AF+WE=,iv:HgJDIiVG29piu7exHKjDKMe9G3fCKepxLVNNGXqFhZk=,tag:l3J439A06dB+pp9y3xVqtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
