apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:J9azAn0Wxt84EQ0C6KJJ5rr68rfskRcWsHyUVhr660i5zeQHn5iDQg==,iv:aQX+V3E5fB8A3av5wucNiuazAa6QMG5RhJ+HGbNDbIo=,tag:gmzpZBrdQWfac8o7VjJ7pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMDNuc0N3UUdFVVRVL0xM
            SlhhT0VoVFBIN204WlRoR3VTT0hnT1FMQUdjCjFJSEhqM2tNdnBUWkJYdGQ2cngw
            VVA1d1h3WlJNNy9QZjVMNWV0UzZxMGMKLS0tIDRpam1mUTRZZjYrcVc5YnlqMU92
            OFh0a3JwYkFIbDZDbDJVM1N5Snlhc0UK0f61+H9P+uAW34zXrPr8/1zOnwLMTXeK
            8irF+k3xWzUNwoIK9Fq+amGtvYiLycSCiqksXgmtHjYy6adscRQrdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T11:35:38Z"
    mac: ENC[AES256_GCM,data:n+F3NmK/+WW0zLcSX/EKQZTRYk7GEHa4n3OFK3bFzcMDeJvZJ/+g2r5WCz0TANkq9lLs5UQevX+uucxBo8DQNz4jQcCMDxKQwivO2AJ5ADq5+B48AqTuh4rhjT1snGkC8J1YZ/eTK4gs5sFHOundagAxzkBhInHdIFCRYnV2V10=,iv:qPgZAYPnFKrFxvvMC1nuMw+ITULV4e71jegRrAFBD1c=,tag:vKWj8jWUWFrpFbt99n29JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
