apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uMggzIUwnwwSVKUi8/VbAYY4Yh9B+ssp2A==,iv:+AItqJ8v3vdyx6FRhgYXM5rB5qP6giBltf6Sr4ekXEw=,tag:8BB/r8cSBkLg1HSv0rcuNQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:w0l8RvER6pPSvRRBd6jJ9oksHsHb35jv/G1/0f9Gkxk=,iv:pwR7i7eawTDVT8Q3lKH1tNzdaDB4VHFKpIYFfDZa0HE=,tag:a6fCyNW8aSRGqZe//CLXdw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rdq1+05SY+FB4T3YOLzM5fOG4uMxagVjBQl5YbJcqAjJZsHr,iv:MKOMaIF/y7/OhX85BndqKorUM9UWf5adXaRk6qZpXL4=,tag:1khaRvoMvggvrIIwMaZ3Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2K29KYUlNRDlJS1lxZlpi
            MnVKcS9NS213VmhCak1jeTdiaWt1cmtURkc0CklZdVgvQ1JqNVV3YTl6MmpLalRz
            VThiNlRoU2F6c1B6cHlCQnV4WDNRaU0KLS0tIGJBZWlRQmFyb1NIZFpqTzYrU20w
            UEF4dWNkZlJuMWE0QTlrOVNDVlVVZTQKPz5qo2HyFRN6GU8XekvK6LtKdbJJKFGh
            s1x4tC2H+xpKGlo5Kk9BZe1Vu0tP1P5c8M0s17FrIJ/T/i3BpC4t2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T13:11:01Z"
    mac: ENC[AES256_GCM,data:hcG101JVupwJvtS8vJ4039GCq6icKKt1z2QcX4G2auC1+RBqX1Pw3ApMqMGivKh93FWMS+V5L+xWEMWVTYJmXZOJDqvSNNPCUdTRVhTEQBgWgEbpQ3wbsXDbIES8pszzRaDBb3O+mfR41AQ/0WYQ/S/B1TNQdcYJD0OfZyKJnmI=,iv:jxQU/tDr9USQD8010ulq5oLKvB7tDTZh/6UuSc1YDtI=,tag:nTkR9Or7iBe7xzSa1FoNww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
