apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tvYhRGWb/a+glDX+LbCt,iv:6jC7gA8g484XgqbAxnA1svQ3rucNpptPlp1mupQdFrQ=,tag:fGdY7EqPMKgLJOw96TGPBg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fQi9k+5dTQlmxbue22oxOzlXpQVfKjj5HWQrsWu7veQ=,iv:ntYUA4UpB5c2qD4nKuxhL6OBaiXkDYSBQYKSb+CZ0co=,tag:oaAMkdY9tKPvZ2x7G5b1qw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:D0jPKaBZ4Le6F7Q1Q7HF89E5/j4uWS5YpTtaWPyM/qQ4YhCV,iv:NwZdGLnsQk3txJFfjxB+/Osrg3HlYFkR+JnFvSa3txw=,tag:r0Yg6X6p0msGqUNsxawVOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZDZIeUVUSDZRRGg4NGVZ
            WmVaaXJRZVRvMlkrTlU5SFNGeUQzRlFaZVRRCmlhZ3pMUVFCYklic1ZnRGg5SnlW
            bG1saEx5YXN3Vnl2Z2N0M05qVlZtZ00KLS0tIHdubU1iTkZWUzhWSUJLSTZLYjdi
            MndTd3JpVE4wbGJRY0V4ZGJMalV5SEEKonp/3ar79S2M8Wipp5TPLuAoyiQQiNSb
            59pJkwTxs0nmxPtV73O1HtipzyfPESBk652UnLAcgjsda4ryav6MDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T19:36:50Z"
    mac: ENC[AES256_GCM,data:In7Znet/gHrEhv4PQZ4Pwz13a+ibB/NEf4K+w8YBwUIdaTSULGleukBz/H2FCcJpCkBreO34RI0vVjRBMRGv0U6x+JT5ArWscV2PIjGD6jQXq1Sd7GD1zePh960M+f6eMTUd4yEVjKOC5xosbwSnmN+jKy/ZyJ7YnVEIrESaIKM=,iv:9Wdq5luMb6gFeTuGpoVkotOT/u1N4+ClcoLVepUB+Qk=,tag:L/q075qD4/24YcGb+nlfXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
