apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YQbz6j7e9DlwJqxY30Up,iv:jKLKVAXTDHBloMh4Lo9lF1GJvlf6UXdVUT+KPD9J5X0=,tag:I9hf+rvGooBuM4HjI7+1WA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LptU4XXukMjsFDpIMAYUq5Yqo2goJqEQgshEaszrr48=,iv:lcKt1m3eNIgJaABa93VTllm9vqi0LGFZMtk5SJzIzRw=,tag:3wyHmZ/vGXEOtJXPIgD6FQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gTPjWT19SZZWNu1C1ZhkNPkUc1k25lCRGyrBvOq7QgJPcAw6,iv:AwFnyexa/58BP76u4PCQIF3rvtX4uxshR4QKUeh5CDs=,tag:2EQLh5VDND35LoOf8l6VmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVWNIcloxYkU2OEM5SXpw
            emI1blJzZGt0bDdQU29rQmYrTTRlRUc1NHdBClpIc0Jtd3VFZk9QYlIrQVpvNnQx
            ZEpaSVZVVDUyaHU1aVhLT3RMemRuTVkKLS0tICtLc1ZQYXZxUzNCd1UzbzZTN2dT
            aTlyL3o0WEJBS2FWbkg0V1ROa1VFeXcK6zC03BKXqlCZL3Te/8C7N823OziY+XoA
            Bpv2q6TWyX5ZLpJN7Hxi3lP8nWoYV7oZ1Gl3RVWtgBBGHvJVLJ4aFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T11:35:38Z"
    mac: ENC[AES256_GCM,data:F1Q8PhXsDJZmKDUkgKwSE4Xt4kd4wtT6Dq6xfjbBK4KRddk4TRC0YJbtWqdroBgN8Pcs0224G0wINorJEXkjnTEKaKaqGSE1Eri2dPor3CuyhUvPE1Mipi9gYPpidMGBqv/BfXo8XnPWVLHDTfkOtIj05spt322MOiuu/ma8iAw=,iv:mNTtIQCM41nPpabLCsHNLBhk1YLB5si5GZB9/ygi3mA=,tag:NoMiYG8F2W2kbaaaHASGrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
