apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:E0X7xuurE+VqjmBHIThp4mxVlkNw0pz/4GowNEJFvuk=,iv:wEwhu8jhXzepPtwQg/Fg7UUDO4MQ/YlMj5m6syikc3Y=,tag:Ke2OTJyy3db4fLvSx3AdAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb0V1Nmp2MEVVdFZnWk5V
            TTBkYjZTb29NaENuWVFhZGNQK1B0Q1p2R0gwCk5pSnFOVEJLd3p5eXVCMHFEQjlF
            ZnRENGVHeGoraTlzR3kwamRlSzRVSEUKLS0tIEljVlBNZnhTazk3QnN1amw5U09E
            UlAybFVkMkpRbHBNNjlDMjRiSVd2UncKjNNOiADAdLcKS9GwWblC/ytztIP6dQ7Z
            E+WTvLBFYAW4eBHihke01c5YgdWCrN2zlds6Rb7Pd6bHa/3eR575fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T11:35:38Z"
    mac: ENC[AES256_GCM,data:npOgVYkTK8i3Raa4y9vQkEb5VwCkGe7u6ZAQkvE4IGhmj8kX9Oo2rBaJI6HBlZYvJo42c0NfOXfoaMJQy+jj1i0aHDYdMAEGP84TelkK8UsP0JOANTAwPiQ+4lKm09OtLfY4QWhh1G1YMxnOjy5hzYsLz3JhAR2itfiD0CuVFcY=,iv:lL3XpdxPr553ym2E616BDWZJriolMNxhGnUMPW4/Xx4=,tag:QFQbndT2FY+3yPSk3reFwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
