apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:u/Cy8EhndnOsuuLILFmpqpBywg6NEVz4hrbulVLnteY=,iv:7mL+HNv8mTnx9LawbWe2sAPpyB7kbmO87beeaw/WOgY=,tag:uB06G5Z2VuKkCs8mLkH2SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbzZYcjhwL09xUWZiRHZp
            VkJ2QkMrcEhVZnRkeThJSWR4MVJYMU9GK2tVClpCMUpIc1BCT2NLR3c3S1pzWTlu
            MVB5U0ozWGZjeCtndGd5Q291UEJOYnMKLS0tIEFuRkVUaE4xcDMyVTVqemtSV0Vz
            bEJmZGZ6T1ZmNmpjZXRIRHZJSVlseGcKb5qK2iWTrhA3YT7CIfSn2mKDxu6321+x
            zC2n0icaCkoVzuHqCJPbZDcJPAv0HqSvDTaU249drmN+61rR9Qeavw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T20:30:12Z"
    mac: ENC[AES256_GCM,data:y5HaE/G1RbCNqIawl2EJrxgSBohdaKLLRWxmF1qSH7Q1UyjAMjle28mz1IiZDic+4l5FmlVSn1LS61IDWhYsAGUB7hhEUheH21evkJMa+QYyAGT+bD8y0iDFwTMdJr0qnTXhKgCADeRA/4fyiPfuonGLeFN7FLhIscE6DsEtxaY=,iv:xzXYxOYgNjsPqV0vhR0lpn15mW9iyht/8fp3YMBuHhk=,tag:EsXXomAKe6OL/Q5itgodJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
