apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:86sgkzfzVe7rI2EEA2mvfYj3L/PvpXHmh7rOKLIoSvw=,iv:PcYyG+zFBUln20lMteGlxi4bK6p54rgG8JJPO+P1ZuU=,tag:yKugIFgBO11EGDqJHyl17A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeU9WS2NLUldQL2xlcUps
            dVBUNXlKTTYzajVUUTFxRVdNSGgwQnQxWWdZClp1QkRRQ2VZOUV3SlRXLytjWVU1
            SVJ2VldxV2grY0hITkVieGNzYjdaQkUKLS0tIGI3U3NwUTdCYStXRDNqY2IyRytY
            YjJZRXpPeUVZZDcxWGJLWlhSZ2ViSncKys4oHv6D/73wb4tPvcj6G16Eka2Fu7yh
            1h1Ftx2QFsVvLSm+jORK+CxiM5CbmfSTy983iBz0KFI+OC4RF/lhyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T19:36:50Z"
    mac: ENC[AES256_GCM,data:QqByKEYW3ZWorlDGP9UTJUyEhZFzZNnagQFKDx6iKEh/18cAKA6N+Czd3bgpZQpdN4pt1Fvssl7P3Q+iA83Wq9YT1jS9orGn44hOuNfA5ohqSlsQaM2MjM0jJ4WYVP6mAw/JVLfeI23Zb7nCcTdZRKAhFK+NDHRS+EetpDBv4Kw=,iv:PWVoB425ptnK6xcKTach+dkq3KfFpfcqgDvUovMsJho=,tag:726lyyIrt7I/UE4Yy7RiWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
