apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gxlNj/KGc997FboFs8D0Dz0lSXf94jNdW/qzgMumHovEPmcYRfL+kw==,iv:ddS88UzHx2HmhpPuVqeKq/afLMXoh+F4Jj9TUR5iJDU=,tag:FrsKWVe9i3EAHD1DrxzU7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUnphajRHZ083TVY2MEhs
            UzRDSUZxOHZNbDFZK3E3R1I2dmRvMTliRlhBCm5wSHFRNzRaRTYxOEJLZ29qVmp4
            d3JuZFNsb2tNTEs1cjVXbnVCRGp3VG8KLS0tIFdhajh0WDJub2o0TFZPdHRuU3hr
            UW1xSmdiRHM4Tys5WXpuQ0M5dlB4QzAKN8vGyqpLWvHHjSrQZWwSobyHC6xztUJY
            q9pv2MfxBDrW+ZKkHfbt3yt3b14iWCU93G6/aa4HB5i9FAFSvw1Oog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T11:35:38Z"
    mac: ENC[AES256_GCM,data:DKsY2/ztuXaY5Hbj36K0rd01P4vQ3Pj7I+Ho5rTWJtdjbPny0a/JewoT/lEQAhp0jHYGs260Q0XkLSX5KBZNUUNmjkMgV+OlA3WibzDqjPVA+YT1zmYfEDICfRXkskSqS69BNDzA+vCJA8oqWhMoak3OZZag+sRyqQlvN3iTWj4=,iv:9IJsG60Ev6z96oPSR8wnVSi6YDFE0Y1d2tfF36++0d4=,tag:olQz5QouNePZR+LNPN5XEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
