apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:7+k20VEHOse3/RgSqVKFio/tIR4l9xqWblxKCIEHENTpogfF2saTww==,iv:i1uqe8Z0CDsv/UY2lTfIiGZ3HKie+wOawwweiIaEUlU=,tag:9g8BEmcvFwmXE3GvDBGK4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL3BQa2lUczVsZ3BzK09H
            SmFzWjM0R3plNEY2dUhqTWttNHRaWXZiZzA4CmM2d2V0Y0lZNHoxeURTbzA4ZTJx
            Sm1kbitjcE9RWWYzNkRuRDlYKyt5dVkKLS0tIFJuK2tlbXVXWUVmUkxiMlJlUUhC
            SjYwMWdib21Nc2VJTDI4dHFhQ3ZkUVEK4PLDYfiRDULQ204Bjct1lnaq+tmPbtvx
            iqOVXbRfVFdk9bUu/SRm6aHcfrA6HgLAAsTeOSKTIsvjK3X/+O6CRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T21:15:20Z"
    mac: ENC[AES256_GCM,data:u63HUwoYLuhfw05jcgwWTx7Tp6gEE1+Wb6yVUrTMhCq/GusEM1TKmxSgn3OAAuYEdRqH8AvoID+XpLoe0AbPUYyfLkhyuiBvIpayw4OXXSWha4VWHLtcXyuiw713GFaucPs59kqpybnLDuAXiq3wFNJfml6e6UgSl+st5Ele3EQ=,iv:E045pgGGeBUctDE3tsYBA8vrckVEwea1OJFOEALxJmM=,tag:rFqD6xilGFUqXn64JqbRmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
