apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Cs5VhyGAofk9FNImEkerWzej7UYaRSAiYMgMvwLhaLzcevrP26YA8Q==,iv:qEFt13v4FKwRbKsIiCut1YV/+cLkQCEtQabqLPea0m8=,tag:G8xGL4cA7BTKNWaCQ8ODSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15njewrvdp5sj0r8eqprh6xlucxnl9yf7vtmy4k23azqv7fu4ng3qzga354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcjZCbWwvMWJxdmRxSjIr
            STNyZjhKbWdNVzgzcW50U1ZXMWx1VTZ4UVI4CmxpYjlzU3B1cllobWVBc084Ym1V
            Nm10N1B3Ylc5UTdkWmgvclh4N21KS3MKLS0tIFVoeUJlZzFjTzBneHlJWkNyTXho
            WDFxSUNza0l2UzNyZlV1ajNhM0tJNXMKxlUowcfqaL1USLt2bwnK/55BkP6nrgqi
            FxwhQk5sYNiBGIeI3kR//c0nNxjqEbx66KDKWd6r25n31L2mJ33yRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T13:15:46Z"
    mac: ENC[AES256_GCM,data:Vu86Ip0wOQMHIu7PCafOWagXNGxbGlJGt7jrk8h1oKkm8U2c8DbH9FeLWLPcXaDPcpGdKPTPaUpG/G+rOMIqiJkmaud1zPMiQ6bfkZWNZuiBEEUOpBHeL7fWAqnBf5l8lSMwDLmrKjO8zu3acKybe1GjR4KAQHAk1whbemAEN1U=,iv:JkWFFAlqhmOjuA04qKuCTtoJz2KIbr0YrgCqVvLpSzQ=,tag:jFBUxwjFZMN3sk6L2MhEBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
